# Generated by Django 5.2.6 on 2025-09-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='no description', max_length=255),
            preserve_default=False,
        ),
    ]
